### ISSUE TITLE
Sponsor

### ISSUE THREAD

**Issue by mothership1101** [futzu/m3ufu#1]
Hi Adrian,

I'm working on an experimental project related to inserting SCTE-35 markers in a HLS feed.

Would you be open to a sponsorship opportunity? If so, what's the best way to contact you?

**Comment by futzu** [comment]
Sorry , I'm just now seeing this. You can write me a@slo.me and tell me what you have in mind.

**Comment by futzu** [comment]
Cool. I'm going to close this and we can continue via email.

**Comment by futzu** [comment]
I have replied to you several times.

**Comment by mothership1101** [comment]
Shot you an email last week to a@slo.me. Let me know if you didn't receive it.

**Comment by mothership1101** [comment]
Found your reply in my spam haha. We're good now.
